NEW_PROJECT_NAME = "[data-testid='newProject-name']"
NEW_PROJECT_CREATE_DEMO = "button.success"
NEW_PROJECT_CREATE = "main button.primary"
NEW_PROJECT_NAV_NEW = "a[href='/project/new']"
NEW_PROJECT_NAV_RESTORE = "a[href='/project/restore']"
