SIDEBAR_CURRENT_PROJECT = "[data-testid='sidebar-currentProject']"
SIDEBAR_TEMPLATES = "[data-testid='sidebar-templates']"
SIDEBAR_INVENTORY = "[data-testid='sidebar-inventory']"
SIDEBAR_ENVIRONMENT = "[data-testid='sidebar-environment']"
SIDEBAR_KEYS = "[data-testid='sidebar-keys']"
SIDEBAR_REPOSITORIES = "a[href$='/repositories']"
SIDEBAR_INTEGRATIONS = "[data-testid='sidebar-integrations']"
SIDEBAR_TEAM = "[data-testid='sidebar-team']"
